export type ASTROLOGER = {
    id: number,
    category_names: [],
    celebrity: boolean,
    top_choice: boolean,
    rising_star: boolean,
    created_at: Date,
    updated_at: Date,
    name: string | null,
    is_verified: boolean,
    profile_picture: string | undefined ,
    profile_picture1: null,
    profile_picture2: null,
    profile_picture3: null,
    profile_picture4: null,
    years_of_experience: number,
    charges_per_min: number,
    language: string,
    specialization: string,
    total_number_of_orders: number | null,
    total_number_of_min_chat_with_user: number | null,
    total_number_of_call_chat_with_user: number | null,
    bio: string,
    country: string,
    state:string,
    address: string,
    certificate_of_astrology: string,
    gender: string | null,
    call: boolean,
    chat: boolean,
    chat_time: string | number | null,
    call_time: string | number | null,
    emergency_call: boolean,
    emergency_chat: boolean,
    highest_qualification: string | null,
    degree: string | null,
    School_college_university: string | null,
    form_where_learn_astrologer: string | null,
    instagram: string | null,
    facebook: string | null,
    linkdin: string | null,
    youtube_channel:string |  null,
    website: string | null,
    user: string
  };
  